name: Semantic Release for Apps

on:
  push:
    branches:
      - master
    # paths:
    # - 'modules/**'
permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0

      - name: Get changed directories
        id: changed_dirs
        run: |
          FILE_PATHS=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ 'BEGIN{OFS=FS} { if (NF > 1) { NF--; print } else { print $0 } }')
          echo "::set-output name=dirs::${FILE_PATHS}"
        
      # Update the tag format to include the name of the directory
      - name: Update tag format
        id: update_tag_format
        run: |
          CHANGED_DIRS="${{ steps.changed_dirs.outputs.dirs }}"
          ROOT_CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -v '/')
          if [[ -n "$ROOT_CHANGED" ]]; then
            echo "::set-output name=tag_format::"
          else
            APP_NAME=$(echo "$CHANGED_DIRS" | awk '{print tolower($0)}')
            echo "::set-output name=tag_format::${APP_NAME}-v\${version}"
          fi


      # Determine the path to the CHANGELOG.md file dynamically
      - name: Determine CHANGELOG.md path
        id: changelog_path
        run: |
          APP_DIRS="${{ steps.changed_dirs.outputs.dirs }}"
          ROOT_CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -v '/')
          if [[ -n "$ROOT_CHANGED" ]]; then
            echo "::set-output name=path::./CHANGELOG.md"
          else
            while IFS= read -r dir; do
              if [[ -f "${dir}/CHANGELOG.md" ]]; then
                echo "::set-output name=path::${dir}/CHANGELOG.md"
                exit 0  # Exit loop after finding the first matching changelog file
              fi
            done <<< "$APP_DIRS"
          fi

      # Run semantic release only if CHANGELOG.md path is available
      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
        with:
          tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
          additional_packages: |
            ['@semantic-release/changelog', '@semantic-release/git']
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              ['@semantic-release/changelog', { "changelogFile": "${{ steps.changelog_path.outputs.path }}" }],
              '@semantic-release/github',
              ['@semantic-release/git', { "assets": ["${{ steps.changelog_path.outputs.path }}"] }]
            ]
          # Specify default branches to add support for the `main` branch
          # which semantic-release doesn't have as a default yet.
          branches: |
            [
              'master'
            ]
        if: steps.changelog_path.outputs.path != ''

      - name: Semantic Release Output Summary
        id: semantic_summary
        run: |
          echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
        

      # Run semantic release for each directory if CHANGELOG.md path is available
      # - name: Semantic Release
      #   uses: docker://ghcr.io/codfish/semantic-release-action:v2
      #   id: semantic
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
      #   with:
      #     tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
      #     additional_packages: |
      #       ['@semantic-release/changelog', '@semantic-release/git']
      #     plugins: |
      #       [
      #         '@semantic-release/commit-analyzer',
      #         '@semantic-release/release-notes-generator',
      #         '@semantic-release/changelog',
      #         '@semantic-release/github',
      #         '@semantic-release/git'
      #       ]
      #     # Specify default branches to add support for the `main` branch
      #     # which semantic-release doesn't have as a default yet.
      #     branches: |
      #       [
      #         'master'
      #       ]
      #   if: steps.changelog_paths.outputs.paths != ''

      # - name: Update CHANGELOG.md files
      #   run: |
      #     APP_DIRS="${{ steps.changed_dirs.outputs.dirs }}"
      #     while IFS= read -r dir; do
      #       if [[ -f "${dir}/CHANGELOG.md" ]]; then
      #         echo "Updating ${dir}/CHANGELOG.md with latest release"
      #         # Add your code here to update the CHANGELOG.md file with the latest release information
      #       fi
      #     done <<< "$APP_DIRS"



# name: Semantic Release for Apps

# on:
#   push:
#     branches:
#       - master
#     paths:
#     - 'modules/**'
# permissions: write-all

# jobs:
#   release:
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         id: checkout
#         with:
#           fetch-depth: 0

#       # Get the name of the directory that was changed
#       - name: Get changed directories
#         id: changed_dirs
#         run: |
#           echo "::set-output name=dirs::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ '{print $0}' | sort -u)"

#       # Check if there are any tags available
#       - name: Check for tags
#         id: check_tags
#         run: |
#           if [[ -z $(git tag -l) ]]; then
#             echo "::set-output name=has_tags::false"
#           else
#             echo "::set-output name=has_tags::true"
#           fi

#       # Update the tag format to include the name of the directory
#       - name: Update tag format
#         id: update_tag_format
#         run: |
#           APP_NAME=$(echo "${{ steps.changed_dirs.outputs.dirs }}" | awk '{print tolower($0)}')
#           echo "::set-output name=tag_format::${APP_NAME}-v\${version}"

#         # Add new version to changelog or set initial version if no tags are available
#       - name: Add new version to changelog
#         id: add_version_to_changelog
#         run: |
#             if [[ "${{ steps.check_tags.outputs.has_tags }}" == "true" ]]; then
#             version=$(git describe --tags --abbrev=0)
#             else
#             version="1.0.0"
#             echo "## Changelog" > CHANGELOG.md
#             fi
#             sed -i "s|\[[0-9]\+\.[0-9]\+\.[0-9]\+\]|[${version}] $(date +'%Y-%m-%d')|" CHANGELOG.md
            
#       # https://github.com/marketplace/actions/semantic-release-action#usage
#       - name: Semantic Release
#         uses: docker://ghcr.io/codfish/semantic-release-action:v2
#         id: semantic
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
#         with:
#           tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
#           additional_packages: |
#             ['@semantic-release/changelog', '@semantic-release/git']
#           plugins: |
#             ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG', "changelogFile": "modules/aws/eks/eks-simple/modules/CHANGELOG.md"}], '@semantic-release/github', ['@semantic-release/git', {
#               "assets": ["modules/aws/eks/eks-simple/modules/CHANGELOG.md"]
#             }]]
#           # specify default branches to add support for the `main` branch
#           # which semantic-release doesn't have as a default yet.
#           branches: |
#             [
#               'master'
#             ]
#       # Get the latest version tag
#       - name: Get latest version tag
#         run: |
#           version=$(git describe --tags --abbrev=0)
#           echo "::set-output name=version::$version"

#       - name: Semantic Release Output Summary
#         id: semantic_summary
#         run: |
#           echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
#           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
#           echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
#           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
#         continue-on-error: true